#3(i)
airquality <- airquality
summary(airquality)
#3(ii)
library(reshape2)
air_melt = melt(airquality, id.vars = c("Month", "Day"))
print(air_melt)
#3(iii)
air_melt = melt(airquality, id.vars = c("Month", "Day"))
print(air_melt)
#3(iv)
airquality_cast <-dcast(air_melt,Month+Day~variable)
print(airquality_cast)
#3(v)
airquality_avg <- dcast(air_melt,Month~variable,mean)
print(airquality_avg)